name: Test

on:
  push:
    branches:
      - main
  pull_request:
  # manual trigger
  workflow_dispatch:

jobs:
  validate-json:
    name: Validate JSON
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Validate JSON
        run: |
          if ! jq empty tokens.json; then
            echo "tokens.json is not a valid JSON file."
            exit 1
          fi
